#!/bin/sh
set -eu

ISO_APPLICATION=${ECZOS_ISO_APPLICATION:-ECZOS 0.1.0}
ISO_VOLUME=${ECZOS_ISO_VOLUME:-ECZOS_0_1_0_AMD64}

lb config noauto \
    --mode debian \
    --system live \
    --distribution trixie \
    --architectures amd64 \
    --linux-flavours amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-options "-o APT::Get::Assume-Yes=true" \
    --binary-images iso-hybrid \
    --debian-installer none \
    --bootappend-live "boot=live components quiet splash username=eczos user-fullname=ECZOS hostname=eczos-live" \
    --iso-application "$ISO_APPLICATION" \
    --iso-preparer "EasyComp Zeeland" \
    --iso-publisher "EasyComp Zeeland" \
    --iso-volume "$ISO_VOLUME" \
    "${@}"
