#!/bin/sh
set -eu

lb config noauto \
    --mode debian \
    --system live \
    --distribution trixie \
    --architectures amd64 \
    --linux-flavours amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --binary-images iso-hybrid \
    --debian-installer live \
    --debian-installer-distribution trixie \
    --debian-installer-gui true \
    --bootappend-live "boot=live components quiet splash" \
    --iso-application "ECZOS Development" \
    --iso-preparer "EasyComp Zeeland" \
    --iso-publisher "EasyComp Zeeland" \
    --iso-volume "ECZOS_DEV_AMD64" \
    "${@}"
