#!/bin/sh
set -eu

ISO_APPLICATION=${ECZOS_ISO_APPLICATION:-ECZOS Development}
ISO_VOLUME=${ECZOS_ISO_VOLUME:-ECZOS_DEV_AMD64}

lb config noauto \
    --mode debian \
    --system live \
    --distribution trixie \
    --architectures amd64 \
    --linux-flavours amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-options "-t trixie-security" \
    --binary-images iso-hybrid \
    --debian-installer live \
    --debian-installer-distribution trixie \
    --debian-installer-gui true \
    --bootappend-live "boot=live components quiet splash" \
    --iso-application "$ISO_APPLICATION" \
    --iso-preparer "EasyComp Zeeland" \
    --iso-publisher "EasyComp Zeeland" \
    --iso-volume "$ISO_VOLUME" \
    "${@}"
