[General]
showlogo=true
showClock=true
logo=/usr/share/eczos/branding/login/login-logo.png
type=image
color=#1e73be
fontSize=10
background=/usr/share/eczos/branding/login/login-bg.png
needsFullUserModel=false
